version: 2.0
jobs:
  install:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: circleci/node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: yarn test

  deploy:
    docker:
      - image: circleci/node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build Site
          command: yarn build
      - run:
          name: Send Via SCP
          command: scp -rp -oStrictHostKeyChecking=accept-new build/ $SSH_USER@$SSH_HOST:$SSH_PATH

workflows:
  version: 2
  workflow:
    jobs:
      - install
      - test:
          requires:
            - install
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
